declare const isNull: (value: any) => boolean;
declare const isUndefined: (value: any) => boolean;
declare const isString: (value: any) => boolean;
declare const isValidString: (value: any) => boolean;
declare const isEmptyString: (value: any) => boolean;
declare const isBoolean: (value: any) => boolean;
declare const isFalse: (value: any) => boolean;
declare const isNumber: (value: any) => boolean;
declare const isValidNumber: (value: any) => boolean;
declare const isFunction: (value: any) => boolean;
declare const isArray: (value: any) => boolean;
declare const isValidArray: (value: any) => boolean;
declare const isEmptyArray: (value: any) => boolean;
declare const isObject: (value: any) => boolean;
declare const isValidObject: (value: any) => boolean;
declare const isEmptyObject: (value: any) => boolean;
export { isNull, isUndefined, isString, isValidString, isEmptyString, isBoolean, isFalse, isNumber, isValidNumber, isFunction, isArray, isValidArray, isEmptyArray, isObject, isValidObject, isEmptyObject, };
